# Configuration for release-plz
# https://release-plz.ieni.dev/docs/config

[workspace]
# Enable changelog generation
changelog_update = true

# Customize the changelog path
changelog_path = "CHANGELOG.md"

# Update all workspace dependencies when releasing
dependencies_update = true

# Create git tags for releases
git_tag_enable = true

# Tag format for releases
git_tag_name = "v{{ version }}"

# Enable GitHub releases
git_release_enable = true

# Publish to crates.io
publish = true

# Allow dirty working directory (useful for workspace releases)
allow_dirty = false

# PR settings
pr_name = "chore: release v{{ version }}"
pr_body = """
## Release v{{ version }}

{% for release in releases %}
### {{ release.package_name }} v{{ release.version }}
{% if release.changelog %}
{{ release.changelog }}
{% endif %}
{% endfor %}

---

This PR was created by release-plz.
"""

# Package-specific settings
[[package]]
name = "wow-mpq"
changelog_path = "file-formats/archives/wow-mpq/CHANGELOG.md"

[[package]]
name = "wow-dbc"
changelog_path = "file-formats/database/wow-dbc/CHANGELOG.md"

[[package]]
name = "wow-blp"
changelog_path = "file-formats/graphics/wow-blp/CHANGELOG.md"

[[package]]
name = "wow-m2"
changelog_path = "file-formats/graphics/wow-m2/CHANGELOG.md"

[[package]]
name = "wow-wmo"
changelog_path = "file-formats/graphics/wow-wmo/CHANGELOG.md"

[[package]]
name = "wow-adt"
changelog_path = "file-formats/world-data/wow-adt/CHANGELOG.md"

[[package]]
name = "wow-wdl"
changelog_path = "file-formats/world-data/wow-wdl/CHANGELOG.md"

[[package]]
name = "wow-wdt"
changelog_path = "file-formats/world-data/wow-wdt/CHANGELOG.md"

[[package]]
name = "warcraft-rs"
changelog_path = "warcraft-rs/CHANGELOG.md"
