[package]
name = "wow-wmo"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/wow-wmo"
description = "Parser for World of Warcraft WMO (world map object) files"
readme = "README.md"
keywords = ["wow", "warcraft", "wmo", "world-objects", "gamedev"]
categories = ["game-development", "parser-implementations"]

[dependencies]
thiserror = "2.0"

[dev-dependencies]

[features]
default = []
