blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/wowemulation-dev/warcraft-rs/tree/main/docs
    about: Check our comprehensive documentation for guides and API references
  - name: 💬 Discussions
    url: https://github.com/orgs/wowemulation-dev/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 🚀 Project Status
    url: https://github.com/wowemulation-dev/warcraft-rs/blob/main/README.md#project-status
    about: Check current implementation status and roadmap
  - name: 🔒 Security Policy
    url: https://github.com/wowemulation-dev/.github/blob/main/SECURITY.md
    about: Review our security policy and responsible disclosure process