---
name: Install Script Test

on:
  push:
    branches: [main]
    paths:
      - 'install.sh'
      - '.github/workflows/install-script.yml'

  pull_request:
    branches: [main]
    paths:
      - 'install.sh'
      - '.github/workflows/install-script.yml'

  workflow_dispatch:

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ShellCheck on install script
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: '.'
          format: gcc
          severity: warning

  test-install:
    name: Test Install (${{ matrix.os }})
    needs: [shellcheck]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test install script functionality (simulated)
        shell: bash
        run: |
          # Make script executable
          chmod +x install.sh

          # Test help
          ./install.sh --help

          # Test platform detection function
          bash -c 'source ./install.sh && detect_platform'

      - name: Test script syntax against released version
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        shell: bash
        run: |
          # This will only work after we have at least one release
          # For now, just test the script syntax
          bash -n install.sh

