---
name: Release

on:
  push:
    tags:
      - 'v[0-9]+.*'

  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.1.0)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  # Performance improvements
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_PROFILE_DEV_DEBUG: 0

permissions:
  contents: write
  discussions: write
  packages: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract release version from tag or input
        id: get_version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install minisign for binary signing
        run: |
          cargo install minisign

      - name: Generate ephemeral signing keypair for this release
        run: |
          # Generate ephemeral keypair for this release
          echo "${{ secrets.MINISIGN_PASSWORD }}" | minisign -G -p minisign.pub -s minisign.key -W

      - uses: actions/upload-artifact@v4
        name: Upload public key
        with:
          name: minisign-public-key
          path: minisign.pub

      - uses: softprops/action-gh-release@v2
        name: Create Release
        id: create_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ steps.get_version.outputs.version }}
          title: Release v${{ steps.get_version.outputs.version }}
          prerelease: false
          files: minisign.pub

  # Build all binaries in parallel
  build-binaries:
    name: Build (${{ matrix.target }})
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds using cross for better compatibility
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            binary: warcraft-rs
            use_cross: true
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            binary: warcraft-rs
            use_cross: true
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            binary: warcraft-rs
            use_cross: true
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            binary: warcraft-rs
            use_cross: true
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-latest
            binary: warcraft-rs
            use_cross: true
          - target: armv7-unknown-linux-musleabihf
            os: ubuntu-latest
            binary: warcraft-rs
            use_cross: true

          # Windows
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            binary: warcraft-rs.exe
            use_cross: false
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            binary: warcraft-rs.exe
            use_cross: false
          - target: x86_64-pc-windows-gnu
            os: ubuntu-latest
            binary: warcraft-rs.exe
            use_cross: true

          # macOS
          - target: aarch64-apple-darwin
            os: macos-latest
            binary: warcraft-rs
            use_cross: false
          - target: x86_64-apple-darwin
            os: macos-latest
            binary: warcraft-rs
            use_cross: false

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "release-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}"
          cache-on-failure: true
          cache-all-crates: true

      # Install cross for Linux builds
      - name: Install cross
        if: matrix.use_cross == true
        run: |
          # Use cargo-binstall for faster installation if available
          if command -v cargo-binstall >/dev/null 2>&1; then
            cargo binstall --no-confirm cross
          else
            cargo install cross --git https://github.com/cross-rs/cross
          fi

      # Build using cross or cargo
      - name: Build release binary
        run: |
          if [[ "${{ matrix.use_cross }}" == "true" ]]; then
            cross build --release --target ${{ matrix.target }} --bin warcraft-rs
          else
            cargo build --release --target ${{ matrix.target }} --bin warcraft-rs
          fi
        shell: bash

      - name: Download signing key for binary verification
        uses: actions/download-artifact@v4
        with:
          name: minisign-public-key
          path: .

      - name: Install minisign for binary signing
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            # Install minisign on Windows via cargo
            cargo install minisign
          else
            cargo install minisign
          fi

      - name: Package and cryptographically sign binary archive
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release

          # Create archive
          if [[ "${{ matrix.os }}" == "windows-latest" ]] || [[ "${{ matrix.target }}" == *"windows"* ]]; then
            7z a ../../../warcraft-rs-${{ matrix.target }}.zip ${{ matrix.binary }}
            ARCHIVE="../../../warcraft-rs-${{ matrix.target }}.zip"
          else
            tar czf ../../../warcraft-rs-${{ matrix.target }}.tar.gz ${{ matrix.binary }}
            ARCHIVE="../../../warcraft-rs-${{ matrix.target }}.tar.gz"
          fi

          cd ../../../

          # Generate signing key from secret
          echo "${{ secrets.MINISIGN_PASSWORD }}" | minisign -G -p temp.pub -s minisign.key -W -f

          # Sign the archive
          echo "${{ secrets.MINISIGN_PASSWORD }}" | minisign -S -s minisign.key -m warcraft-rs-${{ matrix.target }}.${{ contains(matrix.target, 'windows') && 'zip' || 'tar.gz' }} -x warcraft-rs-${{ matrix.target }}.${{ contains(matrix.target, 'windows') && 'zip.minisig' || 'tar.gz.minisig' }}

          # Clean up key
          rm minisign.key temp.pub

      - uses: softprops/action-gh-release@v2
        name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          files: |
            warcraft-rs-${{ matrix.target }}.${{ contains(matrix.target, 'windows') && 'zip' || 'tar.gz' }}
            warcraft-rs-${{ matrix.target }}.${{ contains(matrix.target, 'windows') && 'zip.minisig' || 'tar.gz.minisig' }}

  # Publish crates to crates.io after binaries are built
  publish-crates:
    name: Publish to crates.io
    needs: [build-binaries]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust stable toolchain for publishing
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache dependencies for publishing
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "publish-${{ hashFiles('**/Cargo.lock') }}"
          cache-on-failure: true
          cache-all-crates: true

      # Publish crates in dependency order
      # File format crates first (no interdependencies)
      - name: Publish wow-mpq
        run: cargo publish -p wow-mpq --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        continue-on-error: true

      - name: Publish wow-dbc
        run: cargo publish -p wow-dbc --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        continue-on-error: true

      - name: Publish wow-blp
        run: cargo publish -p wow-blp --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        continue-on-error: true

      - name: Publish wow-m2
        run: cargo publish -p wow-m2 --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        continue-on-error: true

      - name: Publish wow-wmo
        run: cargo publish -p wow-wmo --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        continue-on-error: true

      - name: Publish wow-adt
        run: cargo publish -p wow-adt --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        continue-on-error: true

      - name: Publish wow-wdl
        run: cargo publish -p wow-wdl --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        continue-on-error: true

      - name: Publish wow-wdt
        run: cargo publish -p wow-wdt --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        continue-on-error: true

      # Main CLI crate last (depends on others)
      - name: Publish warcraft-rs
        run: |
          # Wait a bit for crates.io to index the dependencies
          sleep 30
          cargo publish -p warcraft-rs --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        continue-on-error: true
