---
name: Release-plz

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Use a PAT with workflow permissions to allow PR creation
          # Set up RELEASE_PLZ_TOKEN in repository secrets
          token: ${{ secrets.RELEASE_PLZ_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Install Rust toolchain
        run: rustup toolchain install stable --no-self-update --profile minimal

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          # Use a PAT with workflow permissions to allow PR creation
          # Set up RELEASE_PLZ_TOKEN in repository secrets
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN || secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
