---
name: Release-plz

on:
  push:
    branches: [main]

  schedule:
    # Run at 00:00 UTC on Monday
    - cron: '0 0 * * 1'

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache release-plz dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: 'release-plz'

      - name: Install release-plz tool
        run: |
          cargo install release-plz

      - name: Create release PR with release-plz
        run: |
          release-plz release-pr \
            --git-token ${{ secrets.GITHUB_TOKEN }} \
            --repo-url https://github.com/${{ github.repository }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

  # Update changelogs and create tags when PR is merged
  release-plz-release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository with full history for release
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust stable toolchain for release
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install release-plz tool
        run: |
          cargo install release-plz

      - name: Execute release with tags and changelogs
        run: |
          release-plz release \
            --git-token ${{ secrets.GITHUB_TOKEN }} \
            --repo-url https://github.com/${{ github.repository }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
